'use client'

import { store } from "@/cartRedux/store"
import { Provider } from 'react-redux';
import EcommerceNavbar from "@/components/EcommerceNavbar"
import { Toaster } from "@/components/ui/toaster"

// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
//   }

const ClientProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return <Provider store={store}>{children}</Provider>;
};
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <Provider store={store}>
      <html lang="en">
        <body>
          {/* <ClientProvider> */}

            <EcommerceNavbar/> 
            {children}
        <Toaster/>
          {/* </ClientProvider> */}
        </body>
      </html>
      </Provider>
    )
  }
  